//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcEcart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryId
    {
        public int categoryId1 { get; set; }
        public string categorycode { get; set; }
        public string categoryName { get; set; }
    }
}
